version: '3.8'
services:
  neocall_front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: neocall_frontend
    ports:
      - "3000:3000"  
    networks:
      - neocall_net

  neocall_back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: neocall_backend
    ports:
      - "3001:3001"
    volumes:
      - ../volumes/neocall/token.json:/app/src/token.json
    env_file:
      - ../env/.env.neocall
    networks:
      - neocall_net

networks:
  neocall_net:
    driver: bridge
